dailyfresh/cart/urls.py
from django.conf.urls import include, url
from django.contrib import admin


from cart import views

urlpatterns = [
    url(r'^add$', views.CartAddView.as_view(),name='add'),
    url(r'^cart_update$', views.CartUpdateView.as_view(),name='update'),
    url(r'^cart_delete$', views.CartDeleteView.as_view(),name='delete'),
    url(r'^carts$', views.cart,name='carts'),


]

dailyfresh/dailyfresh/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^search/', include('haystack.urls')),
    url(r'^', include('user.urls',namespace='user')),
    url(r'^goods/', include('goods.urls',namespace='goods')),
    url(r'^cart/', include('cart.urls',namespace='cart')),
    url(r'^order/', include('order.urls',namespace='order')),
]

dailyfresh/order/urls.py
from django.conf.urls import include, url
from django.contrib import admin


from order import views

urlpatterns = [
    url(r'^place$', views.OrderPlaceView.as_view(),name='place'),
    url(r'^commit$', views.OrderCommitView.as_view(),name='commit'),
    url(r'^pay$', views.OrderPayView.as_view(),name='pay'),
    url(r'^check$', views.OrderCheckView.as_view(),name='check'),



]

dailyfresh/user/urls.py
from django.conf.urls import include, url
from django.contrib import admin


from user import views

urlpatterns = [
    #登录
    url(r'^login$', views.to_login,name='login'),
    #登出
    url(r'^logout$', views.logout_view,name='logout'),
    #忘记密码
    url(r'^rspon_pwd$', views.ForgetPwdView.as_view(),name='rspon_pwd'),
    url(r'^set_new_password/(?P<token>.*)$', views.ResetPwdView.as_view(),name='new_pwd'),
    #注册
    url(r'^register$', views.RegisterView.as_view(),name='register'),
    url(r'^active/(?P<token>.*)$', views.ActiveView.as_view(),name='active'),
    #异步检测用户名是否存在
    url(r'^check_name$', views.check_name,name='check_name'),
    #验证码
    url(r'^verifycode', views.verifycode,name='verifycode'),

    #收货地址
    url(r'^user_center_site$', views.AddressView.as_view(),name='user_center_site'),
    url(r'^user_center_order/(?P<page>\d+)$', views.OrderView.as_view(),name='user_center_order'),
    url(r'^user_center_info$', views.InfoView.as_view(),name='user_center_info'),

    #省市区三级联动
    url(r'^get_province$', views.get_provice,name='get_province'),
    url(r'^get_areas$', views.get_area,name='get_area'),

    #测试form内建表单的使用
    url(r'^register1$',views.register1),
    url(r'^resetpwd$',views.reset)
]

dailyfresh/order/models.py
from django.db import models
from db.base_model import BaseModel

# Create your models here.

class OrderInfo(BaseModel):
    '''订单模型类'''
    PAY_METHOD_CHIOCES = (
        (1,'货到付款'),
        (2,'微信支付'),
        (3,'支付宝'),
        (4,'银联支付'),
    )

    ORDER_STATUS_CHOICES = (
        (1,'待支付'),
        (2,'待发货'),
        (3,'待收货'),
        (4,'待评价'),
        (5,'已完成'),
    )

    order_id = models.CharField(max_length=128,primary_key=True,verbose_name='订单id')
    user = models.ForeignKey('user.User',verbose_name='用户')
    addr = models.ForeignKey('user.UserAddress',verbose_name='地址')
    pay_method = models.SmallIntegerField(choices=PAY_METHOD_CHIOCES,default=3,verbose_name='支付方式')

    #冗余
    total_count = models.IntegerField(default=1,verbose_name='商品数量')
    total_price = models.DecimalField(max_digits=10,decimal_places=2,verbose_name=' 商品总价')

    transit_price = models.DecimalField(max_digits=10,decimal_places=2,verbose_name='运费')
    order_status = models.SmallIntegerField(choices=ORDER_STATUS_CHOICES,default=1,verbose_name='订单状态')
    trade_no = models.CharField(max_length=128,default='',verbose_name='支付编号')

    class Meta:
        db_table = 'df_order_info'
        verbose_name = '订单'
        verbose_name_plural = verbose_name


class OrderGoods(BaseModel):
    '''订单详情，商品模型类'''
    order = models.ForeignKey('OrderInfo',verbose_name='订单')
    sku = models.ForeignKey('goods.GoodsSKU',verbose_name='商品SKU')
    count = models.IntegerField(default=1,verbose_name='商品数目')
    price = models.DecimalField(max_digits=10,decimal_places=2,verbose_name='商品价格')

    class Meta:
        db_table = 'df_order_goods'
        verbose_name = '订单商品'
        verbose_name_plural = verbose_name

dailyfresh/order/views.py
from django.shortcuts import render,redirect
from utils.myutil import LoginRequiredMixin
from django.core.urlresolvers import reverse
from django.http import JsonResponse
from django.views.generic import View
from django.db import transaction
from django.conf import settings
from alipay import AliPay
import datetime
import os
from goods.models import *
from user.models import *
from order.models import *


# Create your views here.

class OrderPlaceView(LoginRequiredMixin,View):

    def post(self,request):

        user = request.user
        sku_ids = request.POST.getlist('sku_ids')

        if not sku_ids:
            return redirect(reverse('cart:carts'))

        conn = settings.REDIS_CONN
        cart_key = 'cart_%d'%user.id

        skus = []
        total_count = 0
        total_price = 0

        for sku_id in sku_ids:
            sku = GoodsSKU.objects.get(id = sku_id)
            count = conn.hget(cart_key,sku_id)
            amount = sku.price*int(count)

            sku.count = count
            sku.amount = amount
            skus.append(sku)
            total_count += int(count)
            total_price += amount

        #运费
        transit_price = 10
        #实付款
        total_pay = total_price+transit_price
        #获取用户的收件地址
        addrs = UserAddress.objects.filter(username_id=user.id)

        sku_ids = '.'.join(sku_ids)
        context = {
            'skus':skus,
            'total_count':total_count,
            'total_price':total_price,
            'transit_price':transit_price,
            'total_pay':total_pay,
            'addrs':addrs,
            'sku_ids':sku_ids
        }
        return render(request,'order/place_order.html',context)


class OrderCommitView(View):

    @transaction.atomic
    def post(self,request):
        '''订单创建'''
        #判断是否登录
        user = request.user
        if not user.is_authenticated():
            return JsonResponse({'res':0,'errmsg':'用户未登录'})

        #接收参数
        addr_id = request.POST.get('addr_id')
        pay_method = request.POST.get('pay_method')
        sku_ids = request.POST.get('sku_ids')

        #校验参数
        if not all([addr_id,pay_method,sku_ids]):
            return JsonResponse({'res':1,'errmsg':'参数不完整'})

        #校验支付方式
        try:
            pay_method = int(pay_method)
        except ValueError:
            return JsonResponse({'res':2,'errmsg':'非法的支付方式'})
        if pay_method not in dict(OrderInfo.PAY_METHOD_CHIOCES).keys():
            return JsonResponse({'res':2,'errmsg':'非法的支付方式'})

        #校验地址
        try:
            addr = UserAddress.objects.get(id = addr_id)
        except UserAddress.DoesNotExist:
            return JsonResponse({'res':3,'errmsg':'地址非法'})

        # todo: 创建订单核心业务

        #组织参数
        #订单id：时间 20171122181630+用户id
        order_id = datetime.datetime.today().strftime('%Y%m%d%H%M%S')+str(user.id)

        #运费
        transit_price = 10

        #总数目总金额
        total_count = 0
        total_price = 0

        try:
            #设置事务保存点
            save_point = transaction.savepoint()

            #todo: df_order_info表添加一条记录
            order = OrderInfo.objects.create(
                order_id = order_id,
                user=user,
                addr = addr,
                pay_method = pay_method,
                total_count = total_count,
                total_price = total_price,
                transit_price = transit_price
            )

            #todo: 用户的订单中有几个商品，需要向df_order_goods表中加入几条数据
            conn = settings.REDIS_CONN
            cart_key = 'cart_%d'%user.id

            sku_ids = sku_ids.split('.')
            for sku_id in sku_ids:
                print(sku_id)
                try:
                    sku = GoodsSKU.objects.get(id = sku_id)
                except:
                    # 回滚
                    transaction.savepoint_rollback(save_point)
                    return JsonResponse({'res':4,'errmsg':'商品不存在'})

                #从redis获取用户所需要购买的商品数量
                count = conn.hget(cart_key,sku_id)

                #todo: 判断商品的库存
                if int(count) > sku.stock:
                    #回滚
                    transaction.savepoint_rollback(save_point)
                    return JsonResponse({'res':6,'errmsg':'商品库存不足'})

                #todo： 向df_order_goods表中添加一条记录
                OrderGoods.objects.create(
                    order = order,
                    sku = sku,
                    count = count,
                    price = sku.price
                )

                #todo: 更新商品的库存和数量
                sku.stock -= int(count)
                sku.sales += int(count)

                #todo: 累加计算订单商品的总数量和总价格
                amount = sku.price*int(count)
                total_count += int(count)
                total_price += amount

            #todo: 更新订单信息表中的商品总数和总价
            order.total_count = total_count
            order.total_price = total_price
            order.save()

            #提交
            transaction.savepoint_commit(save_point)

        except Exception as e:
            #回滚
            transaction.savepoint_rollback(save_point)
            return JsonResponse({'res':7,'errmsg':'下单失败'})

        #todo: 清除用户的购物车对应记录
        conn.hdel(cart_key,*sku_ids)

        return JsonResponse({'res':5,'message':'创建成功'})


class OrderPayView(View):

    def post(self,request):
        user = request.user
        if not user.is_authenticated():
            return JsonResponse({'res':0,'errmsg':'用户未登录'})

        order_id = request.POST.get('order_id')

        if not order_id:
            return JsonResponse({'res':1,'errmsg':'无效的订单id'})

        try:
            print('order_id:%s'%order_id)
            order = OrderInfo.objects.get(order_id=order_id,user_id=user.id,pay_method=3,order_status=1)
        except OrderInfo.DoesNotExist:
            return JsonResponse({'res':2,'errmsg':'订单错误'})

        #业务处理：使用python sdk调用支付宝的支付接口
        #初始化

        app_private_key_string = os.path.join(settings.BASE_DIR,'order/app_private_key.pem')
        alipay_public_key_string = os.path.join(settings.BASE_DIR,'order/alipay_pubilc_key.pem')

        alipay = AliPay(
            appid="2016092000551549",
            app_notify_url=None,  # 默认回调url
            app_private_key_path=app_private_key_string,
            # 支付宝的公钥，验证支付宝回传消息使用，不是你自己的公钥,
            alipay_public_key_path=alipay_public_key_string,
            sign_type="RSA2",  # RSA 或者 RSA2
            debug = True  # 默认False
        )

        #调用支付接口
        subject = "天天生鲜-%s"%order.order_id
        total_pay = order.total_price+order.transit_price

        # 电脑网站支付，需要跳转到https://openapi.alipay.com/gateway.do? + order_string
        order_string = alipay.api_alipay_trade_page_pay(
            out_trade_no= order_id,
            total_amount=str(total_pay),
            subject=subject,
            return_url=None,
            notify_url=None  # 可选, 不填则使用默认notify url
        )

        pay_url = 'https://openapi.alipaydev.com/gateway.do?'+ order_string
        return JsonResponse({'res':3,'pay_url':pay_url})


class OrderCheckView(View):
    def post(self, request):
        user = request.user
        if not user.is_authenticated():
            return JsonResponse({'res': 0, 'errmsg': '用户未登录'})

        order_id = request.POST.get('order_id')

        if not order_id:
            return JsonResponse({'res': 1, 'errmsg': '无效的订单id'})

        try:
            print('order_id:%s' % order_id)
            order = OrderInfo.objects.get(order_id=order_id, user_id=user.id, pay_method=3, order_status=1)
        except OrderInfo.DoesNotExist:
            return JsonResponse({'res': 2, 'errmsg': '订单错误'})

        # 业务处理：使用python sdk调用支付宝的支付接口
        # 初始化

        app_private_key_string = os.path.join(settings.BASE_DIR, 'order/app_private_key.pem')
        alipay_public_key_string = os.path.join(settings.BASE_DIR, 'order/alipay_pubilc_key.pem')

        alipay = AliPay(
            appid="2016092000551549",
            app_notify_url=None,  # 默认回调url
            app_private_key_path=app_private_key_string,
            # 支付宝的公钥，验证支付宝回传消息使用，不是你自己的公钥,
            alipay_public_key_path=alipay_public_key_string,
            sign_type="RSA2",  # RSA 或者 RSA2
            debug=True  # 默认False
        )

        while True:
            response = alipay.api_alipay_trade_query(order_id)
            code = response.get('code')
            print(response)
            print(code)

            if code == '10000' and response.get('trade_status') == 'TRADE_SUCCESS':
                # 支付成功
                # 获取支付宝交易号
                trade_no = response.get('trade_no')
                # 更新订单状态
                order.trade_no = trade_no
                order.order_status = 4
                order.save()
                print('1...')
                return JsonResponse({'res':3,'message':'支付成功'})

            elif code == '40004' or (code == '10000' and response.get('trade_status')=='WAIT_BUYER_PAY'):
                # 等待买家付款1）  业务处理失败，可能一会儿成功
                import time
                print('休眠5秒后，再次查询订单状态')
                time.sleep(5)
                continue
            else:
                #支付出错
                return JsonResponse({'res':4,'errmsg':'支付失败'})

dailyfresh/templates/order/place_order.html
{% extends 'user/bases/base.html' %}
{% load staticfiles %}

{% block title %}
    <title>天天生鲜--商品订单</title>
{% endblock %}
{% block script %}
    <script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
<script type="text/javascript">
    $('#order_btn').click(function() {
        //获取用户选择的地址id，支付方式，要购买的商品id字符串
        addr_id = $('input[name="addr_id"]:checked').val()
        pay_method = $('input[name="pay_style"]:checked').val()
        sku_ids = $(this).attr('sku_ids')
        csrf = $('input[name="csrfmiddlewaretoken"]').val()
        params ={
            'addr_id':addr_id,
            'pay_method':pay_method,
            'sku_ids':sku_ids,
            'csrfmiddlewaretoken':csrf
        }
        $.post('{% url 'order:commit' %}',params,function(data){
            if(data.res == 5){
                alert(data.message)
                window.location.href = '{% url "user:user_center_order" 1 %}'
            }
            else {
                alert(data.errmsg)
            }
        })
        return false

        localStorage.setItem('order_finish',2);

        $('.popup_con').fadeIn('fast', function() {

            setTimeout(function(){
                $('.popup_con').fadeOut('fast',function(){
                    window.location.href = 'goods/index';
                });
            },3000)

        });
    });
</script>
{% endblock %}

{% block pbody %}

	<div class="search_bar clearfix">
		<a href="../goods/index.html" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;提交订单</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>		
	</div>
	
	<h3 class="common_title">确认收货地址</h3>

	<div class="common_list_con clearfix">
		<dl>
			<dt>寄送到：</dt>
            {% for addr in addrs %}
                <dd><input type="radio" name="addr_id" checked value="{{ addr.id }}">{{ addr.address }} （{{ addr.reciname }} 收） {{ addr.phoneNum }}</dd>
            {% endfor %}


		</dl>
		<a href="../user/user_center_site.html" class="edit_site">编辑收货地址</a>

	</div>
	
	<h3 class="common_title">支付方式</h3>	
	<div class="common_list_con clearfix">
		<div class="pay_style_con clearfix">
			<input type="radio" name="pay_style" checked value="1">
			<label class="cash">货到付款</label>
			<input type="radio" name="pay_style" value="2">
			<label class="weixin">微信支付</label>
			<input type="radio" name="pay_style" value="3">
			<label class="zhifubao"></label>
			<input type="radio" name="pay_style" value="4">
			<label class="bank">银行卡支付</label>
		</div>
	</div>

	<h3 class="common_title">商品列表</h3>
	
	<div class="common_list_con clearfix">
		<ul class="goods_list_th clearfix">
			<li class="col01">商品名称</li>
			<li class="col02">商品单位</li>
			<li class="col03">商品价格</li>
			<li class="col04">数量</li>
			<li class="col05">小计</li>		
		</ul>
        {% for sku in skus %}
            <ul class="goods_list_td clearfix">
                <li class="col01">1</li>
                <li class="col02"><img src="{{ sku.image.url }}"></li>
                <li class="col03">{{ sku.tittle }}</li>
                <li class="col04">{{ sku.unite }}</li>
                <li class="col05">{{ sku.price }}元</li>
                <li class="col06">{{ sku.count }}</li>
                <li class="col07">{{ sku.amount }}元</li>
            </ul>
        {% endfor %}



	</div>

	<h3 class="common_title">总金额结算</h3>

	<div class="common_list_con clearfix">
		<div class="settle_con">
			<div class="total_goods_count">共<em>{{ total_count }}</em>件商品，总金额<b>{{ total_price }}元</b></div>
			<div class="transit">运费：<b>{{ transit_price }}元</b></div>
			<div class="total_pay">实付款：<b>{{ total_pay }}元</b></div>
		</div>
	</div>

	<div class="order_submit clearfix">
        {% csrf_token %}
		<a href="javascript:;" sku_ids="{{ sku_ids }}" id="order_btn">提交订单</a>
	</div>	
{% endblock %}

{% block last_one %}
    <div class="popup_con">
		<div class="popup">
			<p>订单提交成功！</p>
		</div>

		<div class="mask"></div>
	</div>
{% endblock %}

{% block overscript %}
<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
<script type="text/javascript">
    $('#order_btn').click(function() {
        //获取用户选择的地址id，支付方式，要购买的商品id字符串
        addr_id = $('input[name="addr_id"]:checked').val()
        pay_method = $('input[name="pay_style"]:checked').val()
        sku_ids = $(this).attr('sku_ids')
        console.info(addr_id,pay_method,sku_ids)
        csrf = $('input[name="csrfmiddlewaretoken"]').val()
        params ={
            'addr_id':addr_id,
            'pay_method':pay_method,
            'sku_ids':sku_ids,
            'csrfmiddlewaretoken':csrf
        }
        $.post('{% url 'order:commit' %}',params,function(data){
            if(data.res == 5){
                alert(data.message)
                window.location.href = '{% url "user:user_center_order" 1 %}'
            }
            else {
                alert(data.errmsg)
            }
        })
        return false

        localStorage.setItem('order_finish',2);

        $('.popup_con').fadeIn('fast', function() {

            setTimeout(function(){
                $('.popup_con').fadeOut('fast',function(){
                    window.location.href = 'goods/index';
                });
            },3000)

        });
    });
</script>
{% endblock %}