dailyfresh/cart/urls.py
from django.conf.urls import include, url
from django.contrib import admin


from cart import views

urlpatterns = [
    url(r'^add$', views.CartAddView.as_view(),name='add'),
    url(r'^cart_update$', views.CartUpdateView.as_view(),name='update'),
    url(r'^cart_delete$', views.CartDeleteView.as_view(),name='delete'),
    url(r'^carts$', views.cart,name='carts'),


]

dailyfresh/dailyfresh/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^search/', include('haystack.urls')),
    url(r'^', include('user.urls',namespace='user')),
    url(r'^goods/', include('goods.urls',namespace='goods')),
    url(r'^cart/', include('cart.urls',namespace='cart')),
    url(r'^order/', include('order.urls',namespace='order')),
]

dailyfresh/goods/urls.py
from django.conf.urls import include, url
from django.contrib import admin


from goods import views

urlpatterns = [
    url(r'^index$', views.IndexView.as_view(),name='index'),
    url(r'^detail/(?P<sid>\d+)/$',views.detail,name='detail'),
    url(r'^list/(?P<type_id>\d+)/(?P<pn>\d+)',views.goodslist,name='goodlist'),


]

dailyfresh/order/urls.py
from django.conf.urls import include, url
from django.contrib import admin


from order import views

urlpatterns = [
    url(r'^place$', views.OrderPlaceView.as_view(),name='place'),
    url(r'^commit$', views.OrderCommitView.as_view(),name='commit'),
    url(r'^pay$', views.OrderPayView.as_view(),name='pay'),
    url(r'^check$', views.OrderCheckView.as_view(),name='check'),



]

dailyfresh/user/urls.py
from django.conf.urls import include, url
from django.contrib import admin


from user import views

urlpatterns = [
    #登录
    url(r'^login$', views.to_login,name='login'),
    #登出
    url(r'^logout$', views.logout_view,name='logout'),
    #忘记密码
    url(r'^rspon_pwd$', views.ForgetPwdView.as_view(),name='rspon_pwd'),
    url(r'^set_new_password/(?P<token>.*)$', views.ResetPwdView.as_view(),name='new_pwd'),
    #注册
    url(r'^register$', views.RegisterView.as_view(),name='register'),
    url(r'^active/(?P<token>.*)$', views.ActiveView.as_view(),name='active'),
    #异步检测用户名是否存在
    url(r'^check_name$', views.check_name,name='check_name'),
    #验证码
    url(r'^verifycode', views.verifycode,name='verifycode'),

    #收货地址
    url(r'^user_center_site$', views.AddressView.as_view(),name='user_center_site'),
    url(r'^user_center_order/(?P<page>\d+)$', views.OrderView.as_view(),name='user_center_order'),
    url(r'^user_center_info$', views.InfoView.as_view(),name='user_center_info'),

    #省市区三级联动
    url(r'^get_province$', views.get_provice,name='get_province'),
    url(r'^get_areas$', views.get_area,name='get_area'),

    #测试form内建表单的使用
    url(r'^register1$',views.register1),
    url(r'^resetpwd$',views.reset)
]

dailyfresh/order/models.py
from django.db import models
from db.base_model import BaseModel

# Create your models here.

class OrderInfo(BaseModel):
    '''订单模型类'''
    PAY_METHOD_CHIOCES = (
        (1,'货到付款'),
        (2,'微信支付'),
        (3,'支付宝'),
        (4,'银联支付'),
    )

    ORDER_STATUS_CHOICES = (
        (1,'待支付'),
        (2,'待发货'),
        (3,'待收货'),
        (4,'待评价'),
        (5,'已完成'),
    )

    order_id = models.CharField(max_length=128,primary_key=True,verbose_name='订单id')
    user = models.ForeignKey('user.User',verbose_name='用户')
    addr = models.ForeignKey('user.UserAddress',verbose_name='地址')
    pay_method = models.SmallIntegerField(choices=PAY_METHOD_CHIOCES,default=3,verbose_name='支付方式')

    #冗余
    total_count = models.IntegerField(default=1,verbose_name='商品数量')
    total_price = models.DecimalField(max_digits=10,decimal_places=2,verbose_name=' 商品总价')

    transit_price = models.DecimalField(max_digits=10,decimal_places=2,verbose_name='运费')
    order_status = models.SmallIntegerField(choices=ORDER_STATUS_CHOICES,default=1,verbose_name='订单状态')
    trade_no = models.CharField(max_length=128,default='',verbose_name='支付编号')

    class Meta:
        db_table = 'df_order_info'
        verbose_name = '订单'
        verbose_name_plural = verbose_name


class OrderGoods(BaseModel):
    '''订单详情，商品模型类'''
    order = models.ForeignKey('OrderInfo',verbose_name='订单')
    sku = models.ForeignKey('goods.GoodsSKU',verbose_name='商品SKU')
    count = models.IntegerField(default=1,verbose_name='商品数目')
    price = models.DecimalField(max_digits=10,decimal_places=2,verbose_name='商品价格')

    class Meta:
        db_table = 'df_order_goods'
        verbose_name = '订单商品'
        verbose_name_plural = verbose_name

dailyfresh/user/models.py
from django.db import models

# Create your models here.
from  django.contrib.auth.models import AbstractUser
from db.base_model import BaseModel

class User(AbstractUser,BaseModel):
    myPhone = models.CharField(max_length=11,null=True)
    myaddress = models.CharField(max_length=100,null=True)
    class Meta:
        db_table = 'df_user'


class UserAddress(models.Model):
    reciname = models.CharField(max_length=10,verbose_name='收件人')
    address = models.TextField(verbose_name='地址')
    postcode = models.CharField(max_length=10,verbose_name='邮编')
    phoneNum = models.CharField(max_length=11,verbose_name='电话号码')
    username = models.ForeignKey(User,verbose_name='用户名')

    class Meta:
        db_table = 'df_user_address'


class AreaContect(models.Model):
    tittle = models.CharField(max_length= 20,verbose_name='地区')
    parent = models.ForeignKey('self',null=True,blank=True)

    def __str__(self):
        return self.tittle

dailyfresh/user/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
from django.core.urlresolvers import reverse
#   序列化
from django.core.serializers import serialize
#   发送邮件
from django.core.mail import send_mail
#  使用celery 发送邮件 使其不延迟
from celery_tasks.tasks import send_email
# 导入setting
from django.conf import settings
# 基于类的视图
from django.views.generic import View
from utils.myutil import LoginRequiredMixin
# python自带的加密解密包 itsdangerous
from itsdangerous import TimedJSONWebSignatureSerializer as tjss, SignatureExpired, BadSignature
# 使用认证系统登录
from django.contrib.auth import authenticate, login, logout
# Create your views here.
from user.models import *
from goods.models import *
from order.models import *
from redis import StrictRedis
#分页
from django.core.paginator import Paginator


class RegisterView(View):
    def get(self, request):
        return render(request, 'user/register.html')

    def post(self, request):
        # 接收注册信息
        user_name = request.POST.get('user_name')
        user_pwd = request.POST.get('pwd')
        user_cpwd = request.POST.get('cpwd')
        user_email = request.POST.get('email')
        user_allow = request.POST.get('allow')
        verifycode = request.POST.get('verifycode', '')

        # 判断验证码是否正确
        if verifycode != request.session['verifycode']:
            errors = {}
            errors['err_veri'] = '验证码错误'
            return render(request, 'user/register.html', {'error': errors})
        # 验证是否可以注册
        user = User.objects.filter(username=user_name)
        if user:
            error = {}
            error['err_2name'] = '用户已存在'
            return render(request, 'user/register.html', {'error': error})
        if user_pwd == user_cpwd:
            user = User.objects.create_user(username=user_name, password=user_pwd, email=user_email)
            user.is_active = 0
            user.save()

            '''验证邮箱'''
            # 加密用户身份信息，生成激活token
            tjs1 = tjss(settings.SECRET_KEY, 1000)
            info = {'confirm': user.id}
            token = tjs1.dumps(info).decode('utf-8')
            encryption_url = 'http://192.168.12.155:8080/active/%s' % token
            # 发邮件
            subject = '天天生鲜欢迎您'
            message = '点击激活'
            sender = settings.EMAIL_FROM
            receiver = [user_email]
            html_message = '<h1>%s,欢迎您成为天天生鲜注册会员</h1>请点击下面的链接激活账户</br><a href="%s">%s</a>' % (
            user_name, encryption_url, encryption_url)

            send_email.delay(subject, message, sender, receiver, html_message=html_message)

            reci = '<h1>%s,恭喜您，注册成功,请查看邮箱激活成为天天生鲜会员</br>' % (user_name)
            return HttpResponse(reci)
        else:
            return redirect(reverse('user:register'))


class ActiveView(View):
    def get(self, request, token):
        """进行用户激活"""
        # 解密，获取需要激活的用户信息
        tjs2 = tjss(settings.SECRET_KEY, 1000)

        # 检查邮箱
        try:
            info = tjs2.loads(token)
            user_id = info['confirm']

            user = User.objects.get(id=user_id)
            user.is_active = 1
            user.save()

            return redirect(reverse('user:login'))
        except SignatureExpired as e:
            return HttpResponse('此链接已过期')
        except BadSignature as e:
            return HttpResponse('此链接不可用')



def check_name(request):
    hname = request.GET.get('hname')
    count = User.objects.filter(username=hname).count()
    users_list = User.objects.filter(username=hname).values('pk')
    info = []
    for i in users_list:
        d = {}
        d['pk'] = i['pk']
        info.append(d)
    context = {
        'ret': info,
        'count': count
    }
    return JsonResponse(context)


def to_login(request):
    if request.method == 'GET':
        reme_name = request.COOKIES.get('reme_name', '')
        return render(request, 'user/login.html', {'reme_name': reme_name})
    else:
        user_name = request.POST.get('username')
        user_pwd = request.POST.get('pwd')
        remerber = request.POST.get('remerber')
        verifycode = request.POST.get('verifycode')
        if verifycode != request.session['verifycode']:
            errors = {}
            errors['err_verify'] = '验证码错误'
            return render(request, 'user/login.html', {'errors': errors})

        user = authenticate(username=user_name, password=user_pwd)
        if user is not None:
            # 用户存在并且已激活
            if user.is_active:
                print("用户通过")
                next_url = request.GET.get('next')
                if next_url:
                    resp = redirect(next_url)
                else:
                    resp = redirect(reverse('goods:index'))
                if remerber == '1':
                    resp.set_cookie('reme_name', user_name, 3600)
                else:
                    resp.delete_cookie('reme_name')
                login(request, user)
                return resp
            # 用户存在但没有激活
            else:
                print("未激活")
                return HttpResponse('该用户尚未激活,如距离注册少于一小时，请去邮箱激活，否则，请重新注册')
        # 用户输入验证错误或者尚未注册
        else:
            print("不存在")
            regis = 'http://192.168.12.155:8080/register'
            logi = 'http://192.168.12.155:8080/login'
            ret = '<h2>登陆时遇到错误,您可能尚未注册或者用户名密码输入错误</h2></br>' \
                  '<h3>1)<a href = %s>注册</a></h3></br><h3>2)<a href = %s>登录</a></h3></br>' % (regis, logi)
            return HttpResponse(ret)


def logout_view(request):
    logout(request)
    return redirect(reverse('goods:index'))


# 忘记密码，通过向邮箱发送邮件进行确认
class ForgetPwdView(View):
    def get(self, request):
        return render(request, 'user/rspon_pwd.html')

    def post(self, request):
        yourname = request.POST.get('yourname')
        email = request.POST.get('email')
        user = User.objects.filter(username=yourname)
        if user:
            '''验证邮箱'''
            # 加密用户身份信息，生成激活token
            tjs1 = tjss(settings.SECRET_KEY, 1000)
            info = {'confirm': user[0].id}
            token = tjs1.dumps(info).decode('utf-8')
            encryption_url = 'http://192.168.12.155:8080/set_new_password/%s' % token
            # 发邮件
            subject = '天天生鲜欢迎您'
            message = '点击激活'
            sender = settings.EMAIL_FROM
            receiver = [email]
            html_message = '<h1>%s,请确定您忘记密码</h1>点击下面的链接重置密码</br><a href="%s">%s</a>' % (
                yourname, encryption_url, encryption_url)

            send_email.delay(subject, message, sender, receiver, html_message=html_message)

            reci = '<h1>%s,重置密码请求成功，请前往邮箱点击链接修改密码</br>' % (yourname)
            return HttpResponse(reci)
        else:
            error = {}
            error['no_name'] = '该用户名还没注册哦！'
            return render(request, 'user/rspon_pwd.html', {'error': error['no_name']})


# 修改密码
class ResetPwdView(View):
    def get(self, request, token):
        tjs2 = tjss(settings.SECRET_KEY, 1000)

        # 检查邮箱
        try:
            info = tjs2.loads(token)
            user_id = info['confirm']
            request.session['user_id'] = user_id

            return render(request, 'user/resetpwd.html')
        except SignatureExpired as e:
            return HttpResponse('此链接已过期')
        except BadSignature as e:
            return HttpResponse('此链接不可用')

    def post(self, request, token):
        new_pwd = request.POST.get('new_pwd')
        user_id = request.session['user_id']
        user = User.objects.get(pk=user_id)
        del request.session['user_id']
        user.set_password(new_pwd)
        user.save()
        return HttpResponse('密码重置成功')


def verifycode(request):
    # 引入绘图模块
    from PIL import Image, ImageDraw, ImageFont
    # 引入随机函数模块
    import random
    # 定义变量，用于画面的背景色、宽、高
    bgcolor = (random.randrange(20, 100), random.randrange(
        20, 100), 255)
    width = 100
    height = 25
    # 创建画面对象
    im = Image.new('RGB', (width, height), bgcolor)
    # 创建画笔对象
    draw = ImageDraw.Draw(im)
    # 调用画笔的point()函数绘制噪点
    for i in range(0, 100):
        xy = (random.randrange(0, width), random.randrange(0, height))
        fill = (random.randrange(0, 255), 255, random.randrange(0, 255))
        draw.point(xy, fill=fill)
    # 定义验证码的备选值
    str1 = 'ABCD123EFGHIJK456LMNOPQRS789TUVWXYZ0'
    # 随机选取4个值作为验证码
    rand_str = ''
    for i in range(0, 4):
        rand_str += str1[random.randrange(0, len(str1))]
    # 构造字体对象
    font = ImageFont.truetype('FreeMono.ttf', 23)
    # 构造字体颜色
    fontcolor = (255, random.randrange(0, 255), random.randrange(0, 255))
    # 绘制4个字
    draw.text((5, 2), rand_str[0], font=font, fill=fontcolor)
    draw.text((25, 2), rand_str[1], font=font, fill=fontcolor)
    draw.text((50, 2), rand_str[2], font=font, fill=fontcolor)
    draw.text((75, 2), rand_str[3], font=font, fill=fontcolor)
    # 释放画笔
    del draw
    # 存入session，用于做进一步验证
    request.session['verifycode'] = rand_str
    # 内存文件操作
    from io import BytesIO
    buf = BytesIO()
    # 将图片保存在内存中，文件类型为png
    im.save(buf, 'png')
    # 将内存中的图片数据返回给客户端，MIME类型为图片png
    return HttpResponse(buf.getvalue(), 'image/png')


class AddressView(LoginRequiredMixin, View):
    def get(self, request):
        ret = request.session['_auth_user_id']
        user_addr = UserAddress.objects.filter(username_id=ret)

        return render(request, 'user/user_center_site.html', {'user_site': user_addr, 'page': 3})

    def post(self, request):
        rname = request.POST.get('reciname')
        addrs = request.POST.get('address')
        postc = request.POST.get('postcode')
        phone = request.POST.get('phoneNum')

        '''MySql数据库实现'''
        # province = request.POST.get('province')
        # province = AreaContect.objects.get(pk = province)
        # city = request.POST.get('city')
        # city = AreaContect.objects.get(pk=city)
        # area = request.POST.get('area')
        # area = AreaContect.objects.get(pk=area)
        # areas = [province.tittle,city.tittle,area.tittle]

dailyfresh/templates/user/login.html
{% extends 'user/bases/login_register.html' %}
{% load static from staticfiles %}

{% block title %}
    <title>天天生鲜-登录</title>
{% endblock %}

{% block ptop %}
	<div class="login_top clearfix">
		<a href="../goods/index.html" class="login_logo"><img src="{% static 'images/logo02.png' %}"></a>
	</div>

	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">日夜兼程 · 急速送达</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="#">立即注册</a>
				</div>
				<div class="form_input">
					<form method="post">
						{% csrf_token %}
                        {% if reme_name != '' %}
                            <input type="text" name="username" class="name_input" placeholder="请输入用户名" value="{{ reme_name }}">
                        {% else %}
                            <input type="text" name="username" class="name_input" placeholder="请输入用户名">
                        {% endif %}
                        <div class="user_error">{{ error.errors }}</div>
						<input type="password" name="pwd" class="pass_input" placeholder="请输入密码">
						<div class="pwd_error">输入错误</div>
                        <input type="text" name="verifycode" class="verify_input" placeholder="请输入验证码"/>
                        <img class="verify_img" src="{% url 'user:verifycode' %}"/>
                        <div class="verify_error">{{ errors.err_verify }}</div>
						<div class="more_input clearfix">
							<input type="checkbox" name="remerber" value="1" checked>
							<label>记住用户名</label>
							<a href="{% url 'user:rspon_pwd' %}">忘记密码</a>
						</div>
						<input type="submit" name="" value="登录" class="input_submit">
					</form>
				</div>
			</div>
		</div>
	</div>
{% endblock %}


	

dailyfresh/templates/user/register.html
{% extends 'user/bases/login_register.html' %}
{% load static from staticfiles %}

{% block title %}
    <title>天天生鲜-注册</title>
{% endblock %}

{% block script %}
    <style type="text/css">
    #verifycode{
	width:200px;height:38px;border:1px solid #e0e0e0;
	float:left;outline:none;text-indent:10px;background-color:#f8f8f8
    }
    </style>
    <script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/register.js' %}"></script>
    <script type="text/javascript">
        $(function () {
            $('#user_name').blur(function () {
                $.ajax({
                    'url':'{% url "user:check_name" %}',
                    'data':{
                        'hname':$('#user_name').val()
                    },
                    'success':function (data) {
                        ret = data.ret
                        count = data.count
                        console.info(ret,count)

                        if (count=='1'){
                            $('.err_name').html('该用户已存在')
                        }
                        else {
                            $('.err_name').html('')
                        }
                    }
                })
            })
        })
    </script>
{% endblock %}

{% block ptop %}
    <div class="register_con">
		<div class="l_con fl">
			<a class="reg_logo"><img src="{% static 'images/logo02.png' %}"></a>
			<div class="reg_slogan">足不出户  ·  新鲜每一天</div>
			<div class="reg_banner"></div>
		</div>

		<div class="r_con fr">
			<div class="reg_title clearfix">
				<h1>用户注册</h1>
				<a href="#">登录</a>
			</div>
			<div class="reg_form clearfix">
				<form action="{% url 'user:register' %}" method="post">
				{% csrf_token %}
                 <ul>
					<li>
						<label>用户名:</label>
						<input type="text" name="user_name" id="user_name">
						<span class="error_tip">提示信息</span>
                        <div class="err_name"></div>
                        <div class="err_2name">{{ error.err_2name }}</div>
					</li>
					<li>
						<label>密码:</label>
						<input type="password" name="pwd" id="pwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>确认密码:</label>
						<input type="password" name="cpwd" id="cpwd">

						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>邮箱:</label>
						<input type="text" name="email" id="email">
						<span class="error_tip">提示信息</span>
					</li>
					<li class="agreement">
						<input type="checkbox" name="allow" id="allow" checked="checked">
						<label>同意”天天生鲜用户使用协议“</label>
						<span class="error_tip2">提示信息</span>
					</li>
                     <li class="verify">
                         <label>输入验证码</label>
                         <input type="text" name="verifycode" id="verifycode"/>
                         <img class="reg_veri" src="{% url 'user:verifycode' %}" alt="loading..."/>
                         <div class="err_2name">{{ error.err_veri }}</div>
                     </li>
					<li class="reg_sub">
						<input type="submit" value="注 册" name="">
					</li>
				</ul>
				</form>
			</div>

		</div>

	</div>
{% endblock %}


dailyfresh/templates/user/register1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register</title>
</head>
<body>
    <h1>Register</h1>

    {% if form.errors %}
        <p style="color: red;">
            Please correct the error{{ form.errors|pluralize }} below.
        </p>
    {% endif %}
    {% for item in error %}
        <p style="color:red;">{{ item }}</p>
    {% endfor %}

    <form action="" method="post">
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Register">
    </form>
</body>
</html>

dailyfresh/templates/user/reset1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>chongzhi </title>
</head>
<body>
    <form action="" method="post">
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="提交">
    </form>
</body>
</html>

dailyfresh/templates/user/resetpwd.html
{% extends 'user/bases/base.html' %}

{% block title %}
    <title>忘记密码</title>
{% endblock %}

{% block script %}
    <style type="text/css">
        #set_newpwd{
            height: 480px;
        }
    </style>
{% endblock %}

{% block pbody %}
    <div id="set_newpwd">
    <form action="{% url 'user:new_pwd' token %}" method="post">
    {% csrf_token %}
        <table cellspacing="0" align="center">
            <tr>
                <td width="100"><label>输入您的新密码:</label></td>
                <td width="200"><input type="text" name="new_pwd"></td>
            </tr>
            <tr>
                <td colspan="2"><input type="submit" value="提交"></td>
            </tr>
        </table>
    </form>
    </div>
{% endblock %}

dailyfresh/templates/user/user_center_info.html
{% extends 'user/bases/user_center.html' %}
{% load static from staticfiles %}
{% block title %}
	<title>天天生鲜-用户中心</title>
{% endblock %}

{% block oright %}

{#	<div class="main_con clearfix"></div>#}
    <div class="right_content clearfix">
        <div class="info_con clearfix">
        <h3 class="common_title2">基本信息</h3>
                <ul class="user_info_list">
                    <li><span>用户名：</span>{{ user }}</li>
                    {% if user.myPhone and user.myaddress %}
                    <li><span>联系方式：</span>{{ user.myPhone }}</li>
                    <li><span>联系地址：</span>{{ user.myaddress }}</li>
                    {% else %}
                        <form action="{% url 'user:user_center_info' %}" method="post">
                        {% csrf_token %}
                            <li><span>联系方式：</span><input type="text" name="phone"></li>
                            <li><span>联系地址：</span><input type="text" name="addr"></li>
                            <li><input type="submit" value="提交"></li>

                        </form>
                    {% endif %}

                </ul>
        </div>
        <h3 class="common_title2">最近浏览</h3>
    <div class="has_view_list">
        <ul class="goods_type_list clearfix">
            {% for goodskus in goodskus %}
               <li>
                    <a href="{% url 'goods:detail' goodskus.id %}"><img src="{{ goodskus.image.url }}"></a>
                    <h4><a href="{% url 'goods:detail' goodskus.id %}">{{ goodskus.tittle }}</a></h4>
                    <div class="operate">
                        <span class="prize">￥{{ goodskus.price }}</span>
                        <span class="unit">{{ goodskus.price }}/{{ goodskus.unite }}</span>
                        <a href="#" class="add_goods" title="加入购物车"></a>
                    </div>
                </li>
            {% endfor %}
        </ul>
    </div>
    </div>


{% endblock %}





dailyfresh/templates/user/user_center_order.html
{% extends 'user/bases/user_center.html' %}
{% load static from staticfiles %}



{% block oright %}

    <div class="right_content clearfix">
        <h3 class="common_title2">全部订单</h3>
        {% for order in order_page.object_list %}

            <ul class="order_list_th w978 clearfix">
                <li class="col01">{{ order.create_time }}</li>
                <li class="col02">订单号：{{ order.order_id }}</li>
                <li class="col02 stress">{{ order.get_order_status_display }}</li>
            </ul>


            <table class="order_list_table w980">
                <tbody>
                    <tr>
                        <td width="55%">
                            {% for ogoods in order.order_skus %}
                            <ul class="order_goods_list clearfix">
                                <li class="col01"><img src="{{ ogoods.sku.image.url }}"></li>
                                <li class="col02">{{ ogoods.sku.tittle }}<em>{{ ogoods.sku.price }}元/{{ ogoods.sku.unite }}</em></li>
                                <li class="col03">{{ ogoods.count }}</li>
                                <li class="col04">{{ ogoods.amount }}元</li>
                            </ul>
                            {% endfor %}
                        </td>
                        <td width="15%">{{ order.total_price|add:order.transit_price }}元</td>
                        <td width="15%">待付款</td>
                        <td width="15%"><a href="#" order_id="{{ order.order_id }}" status="{{ order.order_status }}" class="oper_btn">去付款</a></td>
                    </tr>
                </tbody>
            </table>

        {% endfor %}

        <div class="pagenation">
            {% if order_page.has_previous %}
            <a href="{% url 'user:user_center_order' order_page.previous_page_number %}">上一页</a>
        {% endif %}
        {% for pindex in pages %}
            {% if pindex == order_page.number %}
                <a href="{% url 'user:user_center_order' pindex %}" class="active">{{ pindex }}</a>
            {% else %}
                <a href="{% url 'user:user_center_order' pindex %}">{{ pindex }}</a>
            {% endif %}
        {% endfor %}
        {% if order_page.has_next %}
            <a href="{% url 'user:user_center_order' order_page.next_page_number %}">下一页</a>
        {% endif %}
        </div>
    </div>

{% endblock %}
{% block overscript %}
    <script src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
    <script>
        $('.oper_btn').each(function () {
            status = $(this).attr('status')
            if (status == 1){
                $(this).text('去支付')
            }
            else if (status == 2){
                $(this).text('待发货')
            }
            else if(status ==3){
                $(this).text('待收货')
            }
            else if(status == 4){
                $(this).text('待评价')

            }
            else {
                $(this).text('已完成')
            }
        })
        $('.oper_btn').click(function () {
            status = $(this).attr('status')
            order_id = $(this).attr('order_id')
            if (status == 1){
                csrf = $('input[name="csrfmiddlewaretoken"]').val()
                params = {
                    'order_id':order_id,
                    'csrfmiddlewaretoken':csrf
                }
                $.post('{% url "order:pay" %}',params,function(data){
                    if(data.res == 3){
                        //引导进入支付界面
                        window.open(data.pay_url)
                        //浏览器访问/order/check.获取支付交易的结果
                        //ajax post 传递参数：order_id
                        $.post('{% url "order:check" %}',params,function(data){
                            if(data.res == 3){
                                alert('支付成功')
                                //刷新界面
                                location.reload()
                            }
                            else {
                                alert(data.errmsg)
                            }
                        })

                    }
                    else{
                        alert(data.errmsg)
                    }
                })
            }
        })
    </script>
{% endblock %}



dailyfresh/templates/user/welcom1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>welcome</title>
</head>
<body>
    hello!
</body>
</html>