dailyfresh/cart/urls.py
from django.conf.urls import include, url
from django.contrib import admin


from cart import views

urlpatterns = [
    url(r'^add$', views.CartAddView.as_view(),name='add'),
    url(r'^cart_update$', views.CartUpdateView.as_view(),name='update'),
    url(r'^cart_delete$', views.CartDeleteView.as_view(),name='delete'),
    url(r'^carts$', views.cart,name='carts'),


]

dailyfresh/dailyfresh/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^search/', include('haystack.urls')),
    url(r'^', include('user.urls',namespace='user')),
    url(r'^goods/', include('goods.urls',namespace='goods')),
    url(r'^cart/', include('cart.urls',namespace='cart')),
    url(r'^order/', include('order.urls',namespace='order')),
]

dailyfresh/goods/urls.py
from django.conf.urls import include, url
from django.contrib import admin


from goods import views

urlpatterns = [
    url(r'^index$', views.IndexView.as_view(),name='index'),
    url(r'^detail/(?P<sid>\d+)/$',views.detail,name='detail'),
    url(r'^list/(?P<type_id>\d+)/(?P<pn>\d+)',views.goodslist,name='goodlist'),


]

dailyfresh/order/urls.py
from django.conf.urls import include, url
from django.contrib import admin


from order import views

urlpatterns = [
    url(r'^place$', views.OrderPlaceView.as_view(),name='place'),
    url(r'^commit$', views.OrderCommitView.as_view(),name='commit'),
    url(r'^pay$', views.OrderPayView.as_view(),name='pay'),
    url(r'^check$', views.OrderCheckView.as_view(),name='check'),



]

dailyfresh/cart/models.py
from django.db import models

# Create your models here.

dailyfresh/goods/models.py
from django.db import models
from tinymce.models import HTMLField

# Create your models here.
from db.base_model import BaseModel

class GoodsType(BaseModel):
    tittle = models.CharField(max_length=20,verbose_name='种类名称')
    logo = models.CharField(max_length=20,verbose_name='标识')
    image = models.ImageField(upload_to = 'type',verbose_name='商品类型图片')

    class Meta:
        db_table = 'df_goods_type'
        verbose_name = '商品种类'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.tittle


class GoodsSKU(BaseModel):
    status_chioces = (
        (0,'下架'),
        (1,'上架'),
    )
    type = models.ForeignKey('GoodsType',verbose_name='商品种类')
    goods = models.ForeignKey('Goods',verbose_name='商品SPU')
    tittle = models.CharField(max_length=20,verbose_name='商品名称')
    desc = models.CharField(max_length=256,verbose_name='商品简介')
    price = models.DecimalField(max_digits=10,decimal_places=2,verbose_name='商品单价')
    unite = models.CharField(max_length=20,verbose_name='商品单位')
    image = models.ImageField(upload_to='goods',verbose_name='商品图片')
    stock = models.IntegerField(default=1,verbose_name='商品库存')
    sales = models.IntegerField(default=0,verbose_name='商品销量')
    status = models.SmallIntegerField(default=1,choices=status_chioces,verbose_name='商品状态')

    class Meta:
        db_table = 'df_goods_sku'
        verbose_name = '商品'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.tittle



class Goods(BaseModel):
    tittle = models.CharField(max_length=20,verbose_name='商品SPU名称')
    detail = HTMLField(blank=True,verbose_name='商品详情')
    type = models.ForeignKey('GoodsType',verbose_name='商品种类')

    class Meta:
        db_table = 'df_goods'
        verbose_name = '商品SPU'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.tittle


class GoodsImage(BaseModel):
    sku = models.ForeignKey('GoodsSKU',verbose_name='商品')
    image = models.ImageField(upload_to='goods',verbose_name='图片路径')

    class Meta:
        db_table = 'db_goods_image'
        verbose_name = '商品图片'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.sku.tittle


class IndexGoodsBanner(BaseModel):
    '''首页轮播商品展示模型类'''
    sku = models.ForeignKey('GoodsSKU',verbose_name='商品')
    image = models.ImageField(upload_to='banner',verbose_name='图片')
    index = models.SmallIntegerField(default=0,verbose_name='展示顺序')

    class Meta:
        db_table = 'df_index_banner'
        verbose_name = '首页轮播顺序'
        verbose_name_plural = verbose_name

class IndexTypeGoodsBanner(BaseModel):
    '''首页分类商品展示模型类'''
    DISPLAY_TYPE_CHOICES = (
        (0,'标题'),
        (1,'图片')
    )

    type = models.ForeignKey('GoodsType',verbose_name='商品类型')
    sku = models.ForeignKey('GoodsSKU',verbose_name='商品SKU')
    display_type = models.SmallIntegerField(default=1,choices=DISPLAY_TYPE_CHOICES)
    index = models.SmallIntegerField(default=0,verbose_name='展示顺序')

    class Meta:
        db_table = 'df_index_type_goods'
        verbose_name = '主页分类展示商品'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.sku.tittle

class IndexPromotionBanner(BaseModel):
    '''首页促销活动模型类'''
    title = models.CharField(max_length=20,verbose_name='活动名称')
    url = models.CharField(max_length=256,verbose_name='活动链接')
    image = models.ImageField(upload_to='banner',verbose_name='活动图片')
    index = models.SmallIntegerField(default=0,verbose_name='展示顺序')

    class Meta:
        db_table = 'df_index_promotion'
        verbose_name = '主页促销活动'
        verbose_name_plural = verbose_name

dailyfresh/cart/views.py
from django.shortcuts import render
from django.views.generic import View
from django.http import JsonResponse
from django.conf import settings

from goods.models import *


class CartAddView(View):

    def post(self,request):
        user = request.user
        if not user.is_authenticated():
            return JsonResponse({'res':0,'errmsg':'请先登录'})
        sku_id = request.POST.get('sku_id')
        count = request.POST.get('count')

        if not all([sku_id,count]):
            return JsonResponse({'res':1,'errmsg':'数据不完整'})

        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            return JsonResponse({'res':2,'errmsg':'商品不存在'})

        try:
            count = int(count)
        except Exception as e:
            return JsonResponse({'res':3,'errmsg':'商品数目出错'})

        conn = settings.REDIS_CONN
        cart_key = 'cart_%d'%user.id

        cart_count = conn.hget(cart_key,sku_id)
        if cart_count:
            count+=int(cart_count)
        if count > sku.stock:
            return JsonResponse({'res':4,'errmsg':' 库存不足'})

        conn.hset(cart_key,sku_id,count)
        total_count = get_cart_count(user)
        context = {
            'res': 5,
            'total_count': total_count,
            'message':'添加成功'

        }

        return JsonResponse(context)

def get_cart_count(user):

    total_count = 0

    if user.is_authenticated():
        conn = settings.REDIS_CONN

        cart_key = 'cart_%d'%user.id
        cart_dirt = conn.hgetall(cart_key)

        for sku_id,count in cart_dirt.items():
            total_count += int(count)
    return total_count


def cart(request):
    user = request.user
    if user.is_authenticated():
        conn = settings.REDIS_CONN
        cart_dirt = conn.hgetall('cart_%d'%user.id)

        goodskus = []
        total_count=0
        total_price = 0
        for sku_id, count in cart_dirt.items():
            goodsku = GoodsSKU.objects.get(id = sku_id)
            count = int(count)
            goodsku.count = count
            amount = goodsku.price*count
            goodsku.total_price = amount
            goodskus.append(goodsku)

            total_count += count
            total_price += amount

        context = {
            'goodskus':goodskus,
            'total_count':total_count,
            'total_price':total_price

        }
    else:
        return JsonResponse({'res':0})
    return render(request,'goods/cart.html',context)

class CartUpdateView(View):

    def post(self,request):
        user = request.user
        if not user.is_authenticated():
            return JsonResponse({'res':0,'errmsg':'请先登录'})
        sku_id = request.POST.get('sku_id')
        count = request.POST.get('count')

        if not all([sku_id,count]):
            return JsonResponse({'res':1,'errmsg':'数据不完整'})

        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            return JsonResponse({'res':2,'errmsg':'商品不存在'})

        try:
            count = int(count)
        except Exception as e:
            return JsonResponse({'res':3,'errmsg':'商品数目出错'})

        conn = settings.REDIS_CONN
        cart_key = 'cart_%d'%user.id


        if count > sku.stock:
            return JsonResponse({'res':4,'errmsg':' 库存不足'})

        conn.hset(cart_key,sku_id,count)
        total_count = get_cart_count(user)
        context = {
            'res': 5,
            'total_count': total_count,
            'message':'更新成功'

        }

        return JsonResponse(context)

class CartDeleteView(View):

        def post(self, request):
            user = request.user
            if not user.is_authenticated():
                return JsonResponse({'res': 0, 'errmsg': '请先登录'})
            sku_id = request.POST.get('sku_id')

            if not all([sku_id]):
                return JsonResponse({'res': 1, 'errmsg': '数据不完整'})

            try:
                sku = GoodsSKU.objects.get(id=sku_id)
            except GoodsSKU.DoesNotExist:
                return JsonResponse({'res': 2, 'errmsg': '商品不存在'})

            conn = settings.REDIS_CONN
            cart_key = 'cart_%d' % user.id

            conn.hdel(cart_key, sku_id)
            total_count = get_cart_count(user)
            context = {
                'res': 3,
                'total_count': total_count,
                'message': '删除成功'

            }

            return JsonResponse(context)

dailyfresh/goods/views.py
from django.shortcuts import render
from django.views.generic import View
from django.core.paginator import Paginator

# 使用redis缓存
from django.core.cache import cache
from redis import StrictRedis
# Create your views here.

from goods.models import *

class IndexView(View):
    def get(self,request):
        context = cache.get('index_cache')

        if context == None:

            types = GoodsType.objects.all()

            goods_banners = IndexGoodsBanner.objects.all().order_by('index')

            promotion_banners = IndexPromotionBanner.objects.all().order_by('index')

            for type in types:

                image_banners = IndexTypeGoodsBanner.objects.filter(type=type,display_type=1).order_by('index')
                title_banners = IndexTypeGoodsBanner.objects.filter(type=type,display_type=0).order_by('index')

                type.image_banners = image_banners
                type.title_banners = title_banners


            cart_count = 0

            context = {
                'types':types,
                'goods_banners':goods_banners,
                'promotion_banners':promotion_banners,
                'cart_count':cart_count
            }
            cache.set('index_cache',context,3600)

        return render(request,'goods/index.html',context)


def detail(request,sid):
    types = GoodsType.objects.all()
    goodSKU = GoodsSKU.objects.get(pk = sid)
    goodImage = GoodsImage.objects.get(sku_id=sid)
    goods_list = GoodsSKU.objects.filter(type_id=goodSKU.type_id).order_by('-create_time')[:2]
    same_list = GoodsSKU.objects.filter(goods_id=goodSKU.goods.id).exclude(pk = sid)

    user = request.user
    if user.is_authenticated():
        conn = StrictRedis('192.168.12.155')
        history_key = 'history_%d'%user.id
        conn.lrem(history_key,0,sid)
        conn.lpush(history_key,sid)
        conn.ltrim(history_key,0,4)

    context = {
        'types':types,
        'goodSKU':goodSKU,
        'goodImage':goodImage,
        'goods_list':goods_list,
        'same_list':same_list
    }
    return render(request,'goods/detail.html',context)

def goodslist(request,type_id,pn):
    sort = request.GET.get('sort')
    types = GoodsType.objects.all()
    type = GoodsType.objects.get(id = type_id)
    if sort == 'price':
        goodskus = GoodsSKU.objects.filter(type_id=type_id).order_by('price')
    elif sort == 'hot':
        goodskus = GoodsSKU.objects.filter(type_id=type_id).order_by('-sales')
    else:
        goodskus = GoodsSKU.objects.filter(type_id=type_id)
    goods_list = goodskus.order_by('-create_time')[:2]
    paginator = Paginator(goodskus,4)
    mypage = paginator.page(pn)

    currt_page_num = mypage.number
    range_page = []
    if currt_page_num <= 2:
        range_page = [1, 2, 3]
    elif currt_page_num >= paginator.num_pages - 1:
        range_page = [paginator.num_pages - 2, paginator.num_pages - 1, paginator.num_pages]
    else:
        range_page = list(range(max(currt_page_num - 1, 1), currt_page_num)) + list(
            range(currt_page_num, min(currt_page_num + 1, paginator.num_pages) + 1))

    context = {
        'type':type,
        'types':types,
        'goods_list':goods_list,
        'cart_count':0,
        'mypage':mypage,
        'range_page':range_page,
        'sort':sort
    }
    return render(request,'goods/list.html',context)

dailyfresh/templates/goods/base_goods.html
{% extends 'user/bases/base.html' %}
{% load static from staticfiles %}

{% block checkbox %}
    <div class="search_bar clearfix">
		<a href="{% url 'goods:index' %}" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="search_con fl">
            <form action="/search" method="get">
                <input type="text" class="input_text fl" name="q" placeholder="搜索商品" value="{{ query }}">
                <input type="submit" class="input_btn fr" name="" value="搜索">
            </form>
        </div>
		<div class="guest_cart fr">
			<a href="{% url 'cart:carts' %}" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">0</div>
		</div>
	</div>

	<div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>
				<span></span>
				<ul class="subnav">
                    {% for type in types %}
                        <li><a href="{% url 'goods:goodlist' type.id 1 %}" class="{{ type.logo }}">{{ type.tittle }}</a></li>
                    {% endfor %}


				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="{% url 'goods:index' %}">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

{% endblock %}

dailyfresh/templates/goods/cart.html
{% extends 'user/bases/base.html' %}
{% load staticfiles %}

{% block title %}
    <title>天天生鲜--商品购物车</title>
{% endblock %}

{% block script %}
    <script src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
    <script>
        $(function() {

            //计算商品选中商品总件数和总价格
            function update_page_info() {
            total_count = 0
            total_price = 0
            $('.cart_list_td').find(':checked').parents('ul').each(function () {
                count = $(this).find('.num_show').val()
                amount = $(this).children('.col07').text()
                count = parseInt(count)
                amount = parseFloat(amount)
                total_count += count
                total_price += amount
            })
                $('.total_count em').text(total_count)
                $('.settlements').find('em').text(total_price.toFixed(2))
                $('.settlements').find('b').text(total_count)
            }

            //更新购物车中商品的数量
            error_update = false
            total = 0
            function update_remote_cart_info(sku_id,count) {
                csrf = $('input[name="csrfmiddlewaretoken"]').val()
                params = {'sku_id':sku_id,'count':count,'csrfmiddlewaretoken':csrf}
                $.ajaxSettings.async = false

                $.post('{% url "cart:update" %}',params,function(data){
                    if(data.res == 5){
                        error_update = false
                        total = data.total_count
                    }
                    else {
                        error_update = true
                        alert(data.errmsg)
                    }
                })
                $.ajaxSettings.async = true
            }

            //商品的全选和不全选
            $('.settlements').find(':checkbox').change(function () {
                is_checked = $(this).prop('checked')
            $('.cart_list_td').find(':checkbox').each(function () {
                $(this).prop('checked',is_checked)
            })
            update_page_info()
            })

            //商品对应的checkbox状态发生改变时，设置全部的checkbox的状态
            $('.cart_list_td').find(':checkbox').change(function () {
                all_len = $('.cart_list_td').length
                checked_len = $('.cart_list_td').find(':checked').length
                is_checked = true
                if (checked_len<all_len){
                    is_checked = false
                }
                $('.settlements').find(':checkbox').prop('checked',is_checked)
                update_page_info()
            })

            //点击增加数量
            $(".add").click(function () {
                skuid = $(this).next().attr('sku_id')
                count = $(this).next().val()

                count = parseInt(count)+1


                update_remote_cart_info(skuid,count)

                if(error_update == false){
                    $(this).next().val(count)
                    price = $(this).parents('ul').children('.col05').text()
                    total_price = parseFloat(price)*count
                    console.info(total_price)
                    $(this).parents('ul').children('.col07').text(total_price.toFixed(2)+'元')

                    is_checked = $(this).parents('ul').find(':checkbox').prop('checked')
                    if(is_checked){
                        update_page_info()
                    }
                }
                else {
                    $(this).next().val(total)
                }

            })

            //点击减少数量
            $(".minus").click(function () {
                skuid = $(this).prev().attr('sku_id')
                count = $(this).prev().val()

                count = parseInt(count)-1
                if(count<=1){
                    count = 1
                }

                update_remote_cart_info(skuid,count)

                if(error_update == false){
                    $(this).prev().val(count)
                    price = $(this).parents('ul').children('.col05').text()
                    total_price = parseFloat(price)*count
                    console.info(total_price)
                    $(this).parents('ul').children('.col07').text(total_price.toFixed(2)+'元')

                    is_checked = $(this).parents('ul').find(':checkbox').prop('checked')
                    if(is_checked){
                        update_page_info()
                    }
                }
                else {
                    $(this).prev().val(total)
                }
            })

            //手动输入购物车中的商品数量
            $('.num_show').blur(function () {
                sku_id = $(this).attr('sku_id')
                count = $(this).val()

                if (isNaN(count)||count.trim().length==0||parseInt(count)<=0){
                    $(this).val(pre_count)
                    return
                }
                count = parseInt(count)
                update_remote_cart_info(sku_id,count)
                if (error_update==false){
                    $(this).val(count)
                    price = $(this).parents('ul').children('.col05').text()
                    total_price = parseFloat(price)*count
                    console.info(total_price)
                    $(this).parents('ul').children('.col07').text(total_price.toFixed(2)+'元')

                    is_checked = $(this).parents('ul').find(':checkbox').prop('checked')
                    if(is_checked){
                        update_page_info()
                    }
                    $('.total_count').children('em').text(total)
                }
                else {
                    $(this).val(pre_count)
                }
            })


            //删除购物车中的记录
            $('.cart_list_td').children('.col08').children('a').click(function () {
                sku_id = $(this).parents('ul').find('.num_show').attr('sku_id')
                csrf = $('input[name="csrfmiddlewaretoken"]').val()
                params = {'sku_id':sku_id,'csrfmiddlewaretoken':csrf}
                sku_ul = $(this).parents('ul')
                $.post('/cart/cart_delete',params,function (data) {
                    if (data.res == 3){
                        sku_ul.remove()
                        is_checked = sku_ul.find(':checkbox').prop('checked')
                        if(is_checked){
                            update_page_info()
                        }
                        $('.total_count').children('em').text(data.total_count)
                    }
                    else{
                        alert(data.errmsg)
                    }
                })
            })
            //记录用户输入之前商品的数量
            pre_count = 0
            $('.num_show').focus(function () {
                pre_count = $(this).val()
            })


        })
    </script>

{% endblock %}

{% block pbody %}
	<div class="search_bar clearfix">
		<a href="index.html" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;购物车</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="q" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>		
	</div>

	<div class="total_count">全部商品<em>{{ total_count }}</em>件</div>
	<ul class="cart_list_th clearfix">
		<li class="col01">商品名称</li>
		<li class="col02">商品单位</li>
		<li class="col03">商品价格</li>
		<li class="col04">数量</li>
		<li class="col05">小计</li>
		<li class="col06">操作</li>
	</ul>
    <form action="{% url 'order:place' %}" method="post">
    {% csrf_token %}
    {% for goods in goodskus %}
        <ul class="cart_list_td clearfix">
            <li class="col01"><input type="checkbox" name="sku_ids" value="{{ goods.id }}" checked></li>
            <li class="col02"><img src="{{ goods.image.url }}"></li>
            <li class="col03">{{ goods.tittle }}<br><em>{{ goods.price }}元/{{ goods.unite }}</em></li>
            <li class="col04">{{ goods.unite }}</li>
            <li class="col05">{{ goods.price }}元</li>
            <li class="col06">
                <div class="num_add">
                    <a href="javascript:;" class="add fl">+</a>
                    <input type="text" class="num_show fl" sku_id = "{{ goods.id }}" value="{{ goods.count }}">
                    <a href="javascript:;" class="minus fl">-</a>
                </div>
            </li>
            <li class="col07">{{ goods.total_price }}元</li>
            <li class="col08"><a href="javascript:;">删除</a></li>
        </ul>
    {% endfor %}

	<ul class="settlements">
		<li class="col01"><input type="checkbox" name="" checked=""></li>
		<li class="col02">全选</li>
		<li class="col03">合计(不含运费)：<span>¥</span><em>{{ total_price }}</em><br>共计<b>{{ total_count }}</b>件商品</li>
		<li class="col04"><input type="submit" value="去结算" style="text-align: center;font-size: 24px;"></li>
	</ul>
    </form>
{% endblock %}

dailyfresh/templates/goods/list.html
{% extends 'goods/base_goods.html' %}
{% load static from staticfiles %}

{% block title %}
    <title>天天生鲜--商品列表</title>
{% endblock %}

{% block pbody %}

	<div class="breadcrumb">
		<a href="#">全部分类</a>
		<span>></span>
		<a href="#">{{ type.tittle }}</a>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
                    {% for goods in goods_list %}
                    <li>
						<a href="{% url 'goods:detail' goods.id %}"><img src="{{ goods.image.url }}"></a>
						<h4><a href="{% url 'goods:detail' goods.id %}">{{ goods.tittle }}</a></h4>
						<div class="prize">￥{{ goods.price }}</div>
					</li>
                    {% endfor %}

                </ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<div class="sort_bar">
				<a href="{% url 'goods:goodlist' type.id 1 %}" {% if sort != 'price' %}class="active"{% endif %}>默认</a>
				<a href="{% url 'goods:goodlist' type.id 1 %}?sort=price" {% if sort == 'price' %}class="active"{% endif %}>价格</a>
				<a href="{% url 'goods:goodlist' type.id 1 %}?sort=hot" {% if sort == 'hot' %}class="active"{% endif %}>人气</a>
			</div>

			<ul class="goods_type_list clearfix">
                {% for goodsku in mypage.object_list %}
                <li>
					<a href="{% url 'goods:detail' goodsku.id %}"><img src="{{ goodsku.image.url }}"></a>
					<h4><a href="{% url 'goods:detail' goodsku.id %}">{{ goodsku.tittle }}</a></h4>
					<div class="operate">
						<span class="prize">￥{{ goodsku.price }}</span>
						<span class="unit">{{ goodsku.price }}/{{ goodsku.unite }}</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>
                {% endfor %}

			</ul>

			<div class="pagenation">
                <a style="font-size: 20px" href="{% url 'goods:goodlist' type.id 1 %}?sort={{ sort }}" title="{{ 1 }}">首页</a>
                {% if mypage.has_previous %}
                    <a style="font-size: 20px" href="{% url 'goods:goodlist' type.id mypage.previous_page_number %}?sort={{ sort }}" title="{{ mypage.previous_page_number }}">上一页</a>
                {% else %}
                    <a style="font-size: 20px">上一页</a>
                {% endif %}
                    {% for i in range_page %}
                        <a style="font-size: 20px" href="{% url 'goods:goodlist' type.id i %}?sort={{ sort }}" title="{{ i }}">{{ i }}</a>
                    {% endfor %}
                {% if mypage.has_next %}
                    <a style="font-size: 20px" href="{% url 'goods:goodlist' type.id mypage.next_page_number %}?sort={{ sort }}" title="{{ mypage.next_page_number }}">下一页</a>
                {% else %}
                    <a style="font-size: 20px">下一页</a>
                {% endif %}
                    <a style="font-size: 20px" href="{% url 'goods:goodlist' type.id mypage.paginator.num_pages %}?sort={{ sort }}" title="{{ mypage.paginator.num_pages }}">尾页</a>

			</div>
		</div>
	</div>

{% endblock %}